What is Numpy? Firstly>... 
It's a library for processing Number faster on Python


<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

In [91]:
import numpy as np
import sys

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [3]:
type(np.array([1, 2, 3, 4]))

numpy.ndarray

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
b = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [33]:
z0 = a[1], a[1:], a[1:3], a[1:-1], a[:-1], a[::2], a[2::2]

In [29]:
type(z0)

tuple

In [31]:
z1 = a[[0,3,4]]

In [34]:
type(z1)

numpy.ndarray

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Types! 

In [6]:
a.dtype

dtype('int32')

In [7]:
b.dtype

dtype('float64')

In [13]:
c = np.array([1,2,3,4], dtype=float) # dtype = np.float

In [14]:
c.dtype

dtype('float64')

In [16]:
np.array(['a','b','c']).dtype

dtype('<U1')

In [23]:
d = np.array([{'a': 1}]).dtype

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Matrix Dimensions and Shapes!

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [28]:
A.shape, A.ndim, A.size

((2, 3), 2, 6)

In [29]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [31]:
B.shape, B.ndim, B.size

((2, 2, 3), 3, 12)

In [32]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\Doc\AppData\Local\Temp/ipykernel_11016/548599459.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  C = np.array([


In [39]:
C.shape, C.ndim, C.size, type(C[0])

((2,), 1, 2, list)


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Indexing and Slicing of Matrices

In [2]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [7]:
A[0,:]

array([1, 2, 3])

In [8]:
A[:,0]

array([1, 4, 7])

In [18]:
A[[0,1],:]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
A[:,[0,1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [19]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [21]:
A[1]=np.array([10,10,10])
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [23]:
A[1]=99
A

array([[ 1,  2,  3],
       [99, 99, 99],
       [ 7,  8,  9]])

## Statistical Advantage

In [26]:
a = np.array([1,2,3,4,5])

In [32]:
a.sum(), a.mean(), a.std(), a.var()

(15, 3.0, 1.4142135623730951, 2.0)

In [29]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [34]:
A.sum(), A.mean(), A.std(), A.var()

(45, 5.0, 2.581988897471611, 6.666666666666667)

In [37]:
A.sum(axis=0),  A.sum(axis=1)
A.mean(axis=0), A.mean(axis=1)
A.std(axis=0),  A.std(axis=1)
A.var(axis=0),  A.var(axis=1)

(array([6., 6., 6.]), array([0.66666667, 0.66666667, 0.66666667]))

## Broadcasting and Vectorized operations (ARITHMETIC)

In [40]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [41]:
a + 10, a*10

(array([10, 11, 12, 13]), array([ 0, 10, 20, 30]))

In [43]:
a += 10                 # Update the value
a

array([20, 21, 22, 23])

In [46]:
b = np.array([10, 10, 10, 10])


In [50]:
a + b, a*b

(array([30, 31, 32, 33]), array([200, 210, 220, 230]))

## Boolean Arrays [Logical]

In [52]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [57]:
a[[True, False, False, True, True]]

array([0, 3, 4])

In [58]:
a >= 2

array([False, False,  True,  True,  True])

In [66]:
a.mean

<function ndarray.mean>

In [75]:
a[a>2], a[~(a > a.mean())], a[(a==0) | (a==1)], a[(a==0) & ~(a==1)]         # Power

(array([3, 4]), array([0, 1, 2]), array([0, 1]), array([0]))

In [76]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [80]:
A = np.random.randint(50, size=(3,3))
A

array([[19, 18, 41],
       [ 7, 16, 11],
       [46, 32, 15]])

In [81]:
A > 25

array([[False, False,  True],
       [False, False, False],
       [ True,  True, False]])

In [82]:
A[A>15]

array([19, 18, 41, 16, 46, 32])

## Linear Algebra

In [83]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [89]:
A.dot(B), A@B, A.T, B.T@A

(array([[20, 14],
        [56, 41],
        [92, 68]]),
 array([[20, 14],
        [56, 41],
        [92, 68]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[36, 48, 60],
        [24, 33, 42]]))

# Size of object in Memory

## int and float

In [98]:
sys.getsizeof(1) , np.dtype(int).itemsize, np.dtype(np.int8).itemsize, np.dtype(float).itemsize

(28, 4, 1, 8)

## List memory allocation

In [101]:
sys.getsizeof([1]), np.array([1]).nbytes

(64, 4)

# Performance

In [109]:
a = np.arange(100000)

In [111]:
%time np.sum(a ** 2)

Wall time: 0 ns


332833500

In [114]:
%time sum([l**2 for l in range(100000)])

Wall time: 45.9 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

## Random 

In [116]:
np.random.random(size=2)

array([0.29280495, 0.59542548])

In [117]:
np.random.normal(size=2)

array([-1.93975142,  1.99511425])

In [118]:
np.random.rand(2, 4)

array([[0.2684369 , 0.78018824, 0.7284803 , 0.36134943],
       [0.74098855, 0.53938086, 0.28273416, 0.21383736]])

## Arange

In [119]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [121]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## Reshape

In [122]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [123]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## Linespace

In [126]:
np.linspace(0, 1, 5), np.linspace(0, 1, 20)

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
        0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
        0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
        0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]))

## Zeros, Linespace, Empty

In [127]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [128]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [129]:
np.zeros((3, 3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [130]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [131]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [135]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [132]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

## Identity and Eye

In [136]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [137]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [139]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [142]:
np.eye(8, 4, k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])